#!/bin/bash

JOB="${BUILDKITE_PARALLEL_JOB:=0}"
JOB_COUNT="${BUILDKITE_PARALLEL_JOB_COUNT:=1}"
DEBUG="${DEBUG:=false}"
KEEP_LOGS="${KEEP_LOGS:=false}"

LOG_DIR="${LOG_DIR:=$(mktemp -d)}"
function finish {
  if [ ! $KEEP_LOGS == "true" ]; then
    rm -rf "$LOG_DIR"
  fi
}

trap finish EXIT

function usage {
  echo "This tool will break apart tests to run in parallel on buildkite"
  echo echo "usage:"
  echo "$0 <runner> <test> [<test> ...]"
  echo
  echo "example:"
  echo "$0 make test1 test2"
  echo
  echo "Optional ENV vars:"
  echo "  BUILDKITE_PARALLEL_JOB:"
  echo "    job number must be less then BUILDKITE_PARALLEL_JOB_COUNT-1"
  echo
  echo "  BUILDKITE_PARALLEL_JOB_COUNT:"
  echo "    the number of total jobs"
  echo
  echo "  DEBUG:"
  echo "    set to \"true\" for all logs to be printed"
  echo
  echo "  KEEP_LOGS:"
  echo "    set to \"true\" if you want to keep logs on disk"
  echo
  echo "  LOG_DIR:"
  echo "    the directory the logs are stored in"
  echo "    (defaults to a directory created by mktemp -d)"
}

if [ $# -lt 2 ]; then
 usage
 exit 1 
fi

RUNNER="$1";shift
TESTS=( "$@" )

spinner()
{
    local message=$1; shift
    local pid=$1; shift
    local delay=0.75
    local spinstr='|/-\'
    printf "$message"
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf "\e[2K\e[1000D%s %c" "$message" "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
    done
    printf "\e[2K\e[1000D%s" "$message"
    echo
}

for test_index in ${!TESTS[@]}; do
  test_name="${TESTS[$test_index]}"
  if [ $(( (test_index + JOB) % JOB_COUNT )) -eq 0 ]; then
     message="running $test_name"
    if [ $DEBUG == "true" ] && [ $KEEP_LOGS == "false" ]; then
      printf "$message"
      eval "$RUNNER $test_name"
    elif [ $DEBUG == "true" ] && [ $KEEP_LOGS == "true" ]; then
      eval "$RUNNER $test_name" 2>&1 | tee "$LOG_DIR/$test_name" &
      pid=$!
      spinner "$message" $pid
    else
      eval "$RUNNER $test_name" &> "$LOG_DIR/$test_name" &
      pid=$!
      spinner "$message" $pid
      if ! wait $pid; then
        cat "$LOG_DIR/$test_name"
      fi
    fi
  fi
done
